### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by LucaDev** [orlaqp/angular-snippets#2]
In keymaps\angularjs-snippets.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by orlaqp** [comment]
I will look into it, thanks for reporting it.

**Comment by orlaqp** [comment]
Fixed and released a new version. Please let me know if I can close this issue. Thanks!

**Comment by LucaDev** [comment]
Fixed
